services:
  - type: web
    name: voice-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
    packages:
      - ffmpeg
